# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Utility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  # Pods for Utility
  pod 'AlertHelperKit', :git => 'https://github.com/keygx/AlertHelperKit'
  pod 'KDLoadingView'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'BCryptSwift'
  pod 'ObjectivePGP'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
    end
  end
end
